### ISSUE TITLE
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' 

### ISSUE THREAD

**Issue by change-my-username-droid** [MicrosoftDocs/mslearn-python-products#12]
[Exercise URL](https://learn.microsoft.com/en-us/training/modules/use-docker-container-dev-env-vs-code/2-exercise-prepare-project)

```
vscode ➜ /workspaces/mslearn-python-products (main) $ python app.py
Traceback (most recent call last):
  File "/workspaces/mslearn-python-products/app.py", line 1, in <module>
    from flask import Flask
  File "/home/vscode/.local/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/home/vscode/.local/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/home/vscode/.local/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/home/vscode/.local/lib/python3.11/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/home/vscode/.local/lib/python3.11/site-packages/werkzeug/urls.py)
```

**Comment by Tambros** [comment]
@PioneerWxy  Thank you for this hint. With your hint it works!
